"""add image to posts

Revision ID: d1d533cd24c6
Revises: 82a03ca6e275
Create Date: 2026-05-20 23:10:19.708932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # SQLModel uses ``sqlmodel.sql.sqltypes`` in autogenerated migrations


# revision identifiers, used by Alembic.
revision: str = 'd1d533cd24c6'
down_revision: Union[str, Sequence[str], None] = '82a03ca6e275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image')
    # ### end Alembic commands ###
